# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-07 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATT_ALL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.CharField(max_length=50)),
                ('ErrorDelay', models.CharField(max_length=50)),
                ('Delay', models.CharField(max_length=50)),
                ('TransTimes', models.CharField(max_length=50)),
                ('TransInterval', models.CharField(max_length=50)),
                ('TransFlag', models.CharField(max_length=50)),
                ('Realtime', models.CharField(max_length=50)),
                ('Encrypt', models.CharField(max_length=50)),
                ('ServerVer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ATT_LOG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.CharField(max_length=50)),
                ('User_PIN', models.CharField(max_length=50)),
                ('Verify_Type', models.CharField(max_length=50)),
                ('Verify_Time', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('Work_Code_ID', models.CharField(max_length=50)),
                ('Sensor_NO', models.CharField(max_length=50)),
                ('Att_Flag', models.CharField(max_length=50)),
                ('CREATE_ID', models.CharField(max_length=50)),
                ('MODIFY_TIME', models.CharField(max_length=50)),
                ('SEND_FLAG', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Device_Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CMD', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FINGER_TMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pin', models.CharField(max_length=50)),
                ('FID', models.CharField(max_length=50)),
                ('Size', models.CharField(max_length=50)),
                ('Valid', models.CharField(max_length=50)),
                ('TMP', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='iclock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.CharField(max_length=50)),
                ('options', models.CharField(max_length=20)),
                ('pushver', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=10)),
                ('Stamp', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '教程',
                'verbose_name_plural': '教程',
            },
        ),
        migrations.CreateModel(
            name='OP_LOG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.CharField(max_length=50)),
                ('admin', models.CharField(max_length=50)),
                ('OP', models.CharField(max_length=50)),
                ('OPTime', models.CharField(max_length=50)),
                ('Object', models.CharField(max_length=50)),
                ('Param1', models.CharField(max_length=50)),
                ('Param2', models.CharField(max_length=50)),
                ('Param3', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='USER_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pin', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Pri', models.CharField(max_length=50)),
                ('Pass_Word', models.CharField(max_length=50)),
                ('Card', models.CharField(max_length=50)),
                ('Time_Zones', models.CharField(max_length=50)),
                ('Acc_Group', models.CharField(max_length=50)),
                ('Verify', models.CharField(max_length=50)),
            ],
        ),
    ]
